### PR TITLE
Remove `-xcargs` option and fix extra escaping around xcargs

### LINKED ISSUE #15: xcodebuild: Invalid option -xcargs
It looks like xcodebuild doesn't take an `xcargs` option but instead just takes `<buildsetting>=<value>` pairs directly.

### PR DESCRIPTION
**Pull request by ide**
xcodebuild does not take an -xcargs option since it just takes the key-value pairs directly.

Also multiple key-value pairs need to be provided separately in the command, instead of having quotes around all of them (e.g. `A=1 B=2` instead of `'A=1 B=2'`) so I removed the quoting. This matches the behavior of shenzhen, and my Fastfile that worked with ipa/shenzhen now works with gym with little modification. Since no one could have been relying on xcargs with gym before this commit, I don't think this change should disrupt anyone.

Fixes #15, updated test passes

### CODE REVIEW

File: spec/build_command_generator_spec.rb [hunk 1]
```diff
@@ -7,7 +9,11 @@
     end
 
     it "supports additional parameters" do
-      options = { project: "./example/standard/Example.xcodeproj", sdk: "9.0" }
+      xcargs_hash = { DEBUG: "1", BUNDLE_NAME: "Example App" }
```
Comment (KrauseFx) [inline spec/build_command_generator_spec.rb]: Would it make sense to allow the user to also allow passing a hash and `gym` automatically converts it into a string (like you did in this test)

File: lib/gym/build_command_generator.rb [hunk 2]
```diff
@@ -40,7 +40,7 @@ def options
         options << "-sdk '#{config[:sdk]}'" if config[:sdk]
         options << "-destination '#{config[:destination]}'" if config[:destination]
         options << "-archivePath '#{archive_path}'"
-        options << "-xcargs '#{config[:xcargs]}'" if config[:xcargs]
+        options << config[:xcargs] if config[:xcargs]
```
Comment (KrauseFx) [inline lib/gym/build_command_generator.rb]: Don't we need a `'` around the `config[:xcargs]`?

**Comment by KrauseFx** [comment]
It looks like the `rubocop` tests are failing: https://travis-ci.org/fastlane/gym/builds/75397982

Could you run `rubocop` locally on your machine and fix the styling issues? :+1:

File: lib/gym/build_command_generator.rb (hunk 2 above)
Comment (ide) [inline lib/gym/build_command_generator.rb]: When passing multiple key-value pairs, putting quotes around them confuses xcodebuild. For example "A=1 B=2" gets interpreted as a key called "A" with a value "1 B=2" I believe. So I decided just to match Shenzhen's behavior here.

File: spec/build_command_generator_spec.rb (hunk 1 above)
Comment (ide) [inline spec/build_command_generator_spec.rb]: I think it would be nice to have and remove a lot of confusion (for fastlane users) to use a hash. Maybe in a future commit?

File: lib/gym/build_command_generator.rb (hunk 2 above)
Comment (KrauseFx) [inline lib/gym/build_command_generator.rb]: Sounds good :+1:

File: spec/build_command_generator_spec.rb (hunk 1 above)
Comment (KrauseFx) [inline spec/build_command_generator_spec.rb]: Yes, it's a separate thing, just wanted to know if that makes sense :+1:

**Comment by KrauseFx** [comment]
Thanks @ide for working on this :+1:
